# tasks file for nginx

- name: Install nginx
  apt: 
    name: nginx
    state: present
    update_cache: true

- name: Template nginx file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    register: nginx_config

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: nginx_config.changed