---
- name: "Install dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - lsb-release
    - python3
    - python3-pip
    state: latest
    update_cache: true

- name: "Get Docker APT Key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: "Add Docker APT Repo"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: "Install Docker with Pip"
  pip:
    name: docker
    executable: pip3

- name: "Install Docker"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true
    
- name: Add user to Docker Group
  user:
    name: "{{ lookup ('env','USER') }}"
    groups: docker
    append: yes

  