---
- name: "Install dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates 
    - curl 
    - gnubg 
    - lsb-release
    - python3
    - python3-pip

- name: "Get Docker APT Key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: "Add Docker APT Repo"
  apt_repository:
    repo: "deb https://download.docker.com/linux_ubuntu bionic stable"
    state: present
      
- name: "Install Docker"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    
- name: Add user to Docker Group
  user:
    name: gokeat
    groups: docker
    append: yes

- name: "Install Docker with Pip"
  pip:
    name: docker
    executable: pip3
  